package com.revivex.service;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import com.revivex.domain.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Component; import java.net.URI; import java.net.http.*; import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*;
@Component("razorpayExecution") public class RazorpayExecutionAdapter implements RecoveryExecutionAdapter {
 private final ObjectMapper mapper=new ObjectMapper(); private final String baseUrl,keyId,keySecret,callbackUrl;
 public RazorpayExecutionAdapter(@Value("${revivex.razorpay.base-url}")String baseUrl,@Value("${revivex.razorpay.key-id}")String keyId,@Value("${revivex.razorpay.key-secret}")String keySecret,@Value("${revivex.razorpay.callback-url}")String callbackUrl){this.baseUrl=baseUrl;this.keyId=keyId;this.keySecret=keySecret;this.callbackUrl=callbackUrl;}
 private void configured(){if(keyId.isBlank()||keySecret.isBlank())throw new IllegalStateException("RAZORPAY_NOT_CONFIGURED");}
 private HttpRequest.Builder req(String method,String path){configured();String auth=Base64.getEncoder().encodeToString((keyId+":"+keySecret).getBytes(StandardCharsets.UTF_8));return HttpRequest.newBuilder(URI.create(baseUrl+path)).timeout(Duration.ofSeconds(20)).header("Authorization","Basic "+auth).header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.noBody());}
 private JsonNode call(HttpRequest r){try{HttpResponse<String> x=HttpClient.newHttpClient().send(r,HttpResponse.BodyHandlers.ofString()); if(x.statusCode()<200||x.statusCode()>=300)throw new IllegalStateException("RAZORPAY_HTTP_"+x.statusCode()+" "+x.body()); return mapper.readTree(x.body());}catch(Exception e){throw new IllegalStateException("PAYMENT_LINK_CREATION_FAILED: "+e.getMessage(),e);}}
 public ExecutionResult execute(RecoveryCase c,RecoveryAction a){configured();try{Map<String,Object> body=new LinkedHashMap<>();body.put("amount",c.getPayment().getAmount().multiply(BigDecimal.valueOf(100)).intValueExact());body.put("currency","INR");body.put("accept_partial",false);body.put("reference_id",("RVX"+c.getId()+"-"+a.getIdempotencyKey()).substring(0,Math.min(40,("RVX"+c.getId()+"-"+a.getIdempotencyKey()).length())));body.put("description","ReviveX recovery for case #"+c.getId());body.put("reminder_enable",false);body.put("callback_url",callbackUrl);body.put("callback_method","get");body.put("notes",Map.of("revivex_case_id",String.valueOf(c.getId()),"action",a.getActionType()));String json=mapper.writeValueAsString(body);HttpRequest r=req("POST","/v1/payment_links").method("POST",HttpRequest.BodyPublishers.ofString(json)).build();JsonNode n=call(r);return new ExecutionResult("ACTION_EXECUTED_PENDING",n.path("id").asText(),n.path("short_url").asText(),BigDecimal.ZERO,"Razorpay Test Mode Payment Link created; recovery is pending reconciliation.");}catch(Exception e){throw new IllegalStateException(e.getMessage(),e);}}
 public ExecutionResult reconcile(RecoveryAction a){configured();JsonNode n=call(req("GET","/v1/payment_links/"+a.getProviderReference()).build());String s=n.path("status").asText("created");BigDecimal paid=BigDecimal.ZERO;JsonNode payments=n.path("payments");if(payments.isArray()){for(JsonNode p:payments){paid=paid.add(BigDecimal.valueOf(p.path("amount").asLong(0)).divide(BigDecimal.valueOf(100)));}}String status=s.equals("paid")?"RECOVERED":(s.equals("expired")?"EXPIRED":"PENDING");return new ExecutionResult(status,a.getProviderReference(),n.path("short_url").asText(),paid,"Razorpay Payment Link status reconciled: "+s);} public String mode(){return "razorpay_test";} }
