package com.revivex.service;
import com.revivex.domain.*; import com.revivex.engine.*; import com.revivex.repository.*; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class RecoveryService {
 private final PaymentEventRepository payments; private final RecoveryCaseRepository cases; private final MerchantPolicyRepository policies; private final RecoveryActionRepository actions; private final RecoveryScorer scorer; private final RootCauseEngine rootCause; private final InterventionOptimizer optimizer; private final PolicyEngine policy; private final AuditService audit; private final DemoExecutionAdapter demo; private final RazorpayExecutionAdapter razorpay; private final ExplanationService explanation;
 public RecoveryService(PaymentEventRepository p,RecoveryCaseRepository c,MerchantPolicyRepository m,RecoveryActionRepository a,RecoveryScorer s,RootCauseEngine r,InterventionOptimizer o,PolicyEngine pe,AuditService au,DemoExecutionAdapter d,RazorpayExecutionAdapter rp,ExplanationService ex){payments=p;cases=c;policies=m;actions=a;scorer=s;rootCause=r;optimizer=o;policy=pe;audit=au;demo=d;razorpay=rp;explanation=ex;}
 private RecoveryExecutionAdapter adapter(){return "razorpay_test".equalsIgnoreCase(System.getenv().getOrDefault("REVIVEX_MODE","demo"))?razorpay:demo;}
 @Transactional public List<RecoveryCase> runBatch(){for(PaymentEvent p:payments.findAll()){if(p.isRecovered())continue;if(cases.findAll().stream().anyMatch(c->c.getPayment().getId().equals(p.getId())))continue;String cause=rootCause.classify(p);double probability=scorer.score(p,cause);var choice=optimizer.optimize(p,cause,probability);MerchantPolicy mp=policies.findByMerchant(p.getMerchant()).orElseThrow();var guard=policy.check(p,mp,choice.action());String action=guard.allowed()?choice.action():"STOP";double finalProbability=guard.allowed()?choice.probability():0.02;BigDecimal gross=p.getAmount().multiply(BigDecimal.valueOf(finalProbability)).setScale(2,RoundingMode.HALF_UP);BigDecimal net=gross.subtract(BigDecimal.valueOf(choice.cost())).max(BigDecimal.ZERO).setScale(2,RoundingMode.HALF_UP);String stop=policy.stopRule(p,mp,action);String reasoning=String.format("Root cause=%s. Historical success=%.0f%%. Attempts=%d. Contacts=%d. Selected=%s. Candidate value was compared against bounded alternatives. %s",cause,p.getHistoricalSuccessRate()*100,p.getPreviousAttempts(),p.getPreviousContacts(),choice.action(),guard.reason());RecoveryCase rc=new RecoveryCase(p,cause,action,finalProbability,gross,net,Math.min(.98,.55+Math.abs(finalProbability-.5)),stop,reasoning,guard.reason());cases.save(rc);audit.record(rc.getId(),"CASE_DETECTED","Payment event materialized.");audit.record(rc.getId(),"CASE_ANALYZED","Root cause="+cause);rc.analyzed();audit.record(rc.getId(),"ACTION_PLANNED","Selected="+action+" expectedNet="+net);if(guard.allowed()){rc.planned();rc.approve();cases.save(rc);audit.record(rc.getId(),"POLICY_APPROVED","rule=merchant-policy");}else{rc.blocked();cases.save(rc);audit.record(rc.getId(),"POLICY_BLOCKED","reason="+guard.reason());}}return all();}
 @Transactional public RecoveryCase execute(Long id){RecoveryCase c=cases.findById(id).orElseThrow();if(c.isTerminal())return c;if("STOP".equals(c.getRecommendedAction())){c.stopped();cases.save(c);audit.record(id,"CASE_STOPPED",c.getStoppingRule());return c;}MerchantPolicy mp=policies.findByMerchant(c.getPayment().getMerchant()).orElseThrow();var guard=policy.check(c.getPayment(),mp,c.getRecommendedAction());if(!guard.allowed()){c.blocked();cases.save(c);audit.record(id,"POLICY_BLOCKED",guard.reason());return c;}String key="CASE-"+id+"-"+(c.getAttempts()+1)+"-"+c.getRecommendedAction();Optional<RecoveryAction> existing=actions.findByIdempotencyKey(key);if(existing.isPresent())return c;RecoveryAction a=new RecoveryAction(c,c.getRecommendedAction(),key,adapter().mode(),c.getPayment().getAmount());actions.save(a);c.pending();cases.save(c);try{var result=adapter().execute(c,a);a.executed(result.providerReference(),result.shortUrl(),result.message());actions.save(a);audit.record(id,"ACTION_EXECUTED","mode="+adapter().mode()+" ref="+result.providerReference());if("demo".equals(adapter().mode())){a.simulatedRecovered(result.recovered());actions.save(a);c.recovered(result.recovered());cases.save(c);audit.record(id,"RECOVERY_CONFIRMED","Synthetic confirmed recovery="+result.recovered());}else{c.awaiting();cases.save(c);audit.record(id,"AWAITING_OUTCOME","Payment Link created; actual recovery requires reconciliation.");}}catch(Exception e){a.reconciled("FAILED",BigDecimal.ZERO,e.getMessage());actions.save(a);c.failed();cases.save(c);audit.record(id,"EXECUTION_FAILED",e.getMessage());}return c;}
 @Transactional public List<RecoveryCase> reconcileAll(){for(RecoveryAction a:actions.findByStatus("ACTION_EXECUTED_PENDING")){reconcileAction(a);}return all();}
 @Transactional public RecoveryCase reconcileCase(Long id){List<RecoveryAction> as=actions.findByRecoveryCaseId(id);for(RecoveryAction a:as)if("ACTION_EXECUTED_PENDING".equals(a.getStatus()))reconcileAction(a);return cases.findById(id).orElseThrow();}
 private void reconcileAction(RecoveryAction a){try{var r=adapter().reconcile(a);BigDecimal recovered=r.recovered()==null?BigDecimal.ZERO:r.recovered();if("RECOVERED".equals(r.status())&&recovered.signum()>0){a.reconciled("RECOVERED",recovered,r.message());a.getRecoveryCase().recovered(recovered);cases.save(a.getRecoveryCase());audit.record(a.getRecoveryCase().getId(),"PAYMENT_CONFIRMED","providerRef="+r.providerReference());audit.record(a.getRecoveryCase().getId(),"RECOVERY_CONFIRMED","Actual confirmed recovery="+recovered);}else{a.reconciled(r.status(),recovered,r.message());cases.save(a.getRecoveryCase());audit.record(a.getRecoveryCase().getId(),"OUTCOME_OBSERVED",r.message());}actions.save(a);}catch(Exception e){audit.record(a.getRecoveryCase().getId(),"RECONCILIATION_FAILED",e.getMessage());}}
 public List<RecoveryCase> all(){return cases.findAllByOrderByDecidedAtDesc();} public RecoveryCase get(Long id){return cases.findById(id).orElseThrow();} public List<RecoveryAction> actions(Long id){return actions.findByRecoveryCaseId(id);} public String explanation(Long id){return explanation.explain(get(id));}
 public Map<String,Object> status(){String mode=adapter().mode();boolean configured="demo".equals(mode)||(!System.getenv().getOrDefault("RAZORPAY_KEY_ID","").isBlank()&&!System.getenv().getOrDefault("RAZORPAY_KEY_SECRET","").isBlank());return Map.of("mode",mode,"backend","ONLINE","database","CONNECTED","razorpay",configured?("demo".equals(mode)?"DEMO MODE":"CONFIGURED") : "NOT CONFIGURED","llm",System.getenv().getOrDefault("LLM_ENABLED","false"),"webhook",System.getenv().getOrDefault("RAZORPAY_WEBHOOK_SECRET","").isBlank()?"OPTIONAL":"CONFIGURED","lastReconciliation",Instant.now().toString());}
}
