import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import"./style.css";
const API="http://localhost:8080/api/v1";const money=v=>"₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0});
function Metric({label,value,accent}){return <div className="metric"><span>{label}</span><strong className={accent?"accent":""}>{value}</strong></div>}
function App(){const[dash,setDash]=useState(null),[cases,setCases]=useState([]),[selected,setSelected]=useState(null),[audit,setAudit]=useState([]),[status,setStatus]=useState(null),[busy,setBusy]=useState(false),[tab,setTab]=useState("queue"),[toast,setToast]=useState("");
 async function load(){const [d,c,s]=await Promise.all([fetch(API+"/dashboard").then(r=>r.json()),fetch(API+"/recovery/cases").then(r=>r.json()),fetch(API+"/system/status").then(r=>r.json())]);setDash(d);setCases(c);setStatus(s);if(selected){const f=c.find(x=>x.id===selected.id);if(f)setSelected(f)}} useEffect(()=>{load()},[]);
 async function run(){setBusy(true);await fetch(API+"/recovery/run",{method:"POST"});await load();setBusy(false);setToast("Recovery batch completed");setTimeout(()=>setToast(""),2500)}
 async function openCase(c){setSelected(c);setAudit(await fetch(API+"/recovery/cases/"+c.id+"/audit").then(r=>r.json()))}
 async function execute(){if(!selected)return;setBusy(true);const r=await fetch(API+"/recovery/cases/"+selected.id+"/execute",{method:"POST"});const fresh=await r.json();setSelected(fresh);setAudit(await fetch(API+"/recovery/cases/"+fresh.id+"/audit").then(r=>r.json()));await load();setBusy(false);setToast(fresh.status==="AWAITING_OUTCOME"?"Payment Link created — recovery pending reconciliation":"Action completed");setTimeout(()=>setToast(""),3000)}
 async function reconcile(){setBusy(true);await fetch(API+"/recovery/reconcile",{method:"POST"});await load();if(selected)openCase(cases.find(x=>x.id===selected.id)||selected);setBusy(false);setToast("Reconciliation completed");setTimeout(()=>setToast(""),2500)}
 return <div className="shell"><header><div className="brand"><div className="mark">R</div><div><b>REVIVEX</b><small>AGENTIC REVENUE RECOVERY</small></div></div><div className="headerRight"><span className="live"><i/> {status?.mode?.toUpperCase()||"DEMO"} · {status?.razorpay}</span><button onClick={reconcile} className="ghost">RECONCILE</button><button onClick={run}>{busy?"PROCESSING…":"RUN RECOVERY BATCH"}</button></div></header>
 <main><section className="hero"><div><div className="eyebrow">RAZORPAY BUILDATHON · TRACK 03</div><h1>Revenue recovery,<br/><em>closed-loop.</em></h1><p>Detect leakage. Diagnose the cause. Choose the highest-value intervention. Execute within policy. Reconcile the outcome. Stop when the economics say stop.</p></div><div className="loop">{["DETECT","DIAGNOSE","DECIDE","EXECUTE","RECONCILE","MEASURE"].map(x=><div key={x}>{x}</div>)}</div></section>
 {dash&&<section className="metrics"><Metric label="Recovery opportunity" value={money(dash.cases?dash.cases*0+dash.expectedNetOpportunity:0)} accent/><Metric label="Expected net recovery" value={money(dash.expectedNetOpportunity)} accent/><Metric label="Actual confirmed recovered" value={money(dash.recovered)} accent/><Metric label="Attempted value" value={money(dash.attemptedValue)}/><Metric label="Recovery rate" value={dash.recoveryRate+"%"}/><Metric label="Stopped safely" value={dash.stoppedSafely}/><Metric label="Active cases" value={dash.activeCases}/><Metric label="Escalated" value={dash.escalated}/></section>}
 <div className="statusbar"><span>BACKEND <b>ONLINE</b></span><span>DATABASE <b>CONNECTED</b></span><span>RAZORPAY <b>{status?.razorpay}</b></span><span>WEBHOOK <b>{status?.webhook}</b></span><span>LLM <b>{status?.llm}</b></span></div>
 <nav><button className={tab==="queue"?"selected":""} onClick={()=>setTab("queue")}>RECOVERY QUEUE</button><button className={tab==="analytics"?"selected":""} onClick={()=>setTab("analytics")}>ANALYTICS</button><button className={tab==="architecture"?"selected":""} onClick={()=>setTab("architecture")}>AGENT LOGIC</button></nav>
 {tab==="queue"?<div className="workspace"><section className="panel"><div className="panelTitle"><div><h2>Recovery queue</h2><p>Every unresolved revenue event becomes a bounded case.</p></div><span>{cases.length} CASES</span></div><div className="rows">{cases.map(c=><div className={"caseRow "+(selected?.id===c.id?"active":"")} key={c.id} onClick={()=>openCase(c)}><div className="customer"><b>{c.payment.customer}</b><small>{c.payment.merchant} · {c.payment.channel}</small></div><div><small>VALUE</small><b>{money(c.payment.amount)}</b></div><div><small>ROOT CAUSE</small><span>{c.rootCause}</span></div><div><small>ACTION</small><span className={"chip "+(c.recommendedAction==="STOP"?"stop":"")}>{c.recommendedAction}</span></div><div><small>PROB.</small><b>{Math.round(c.recoveryProbability*100)}%</b></div></div>)}</div></section>
 <section className="panel inspector">{selected?<><div className="panelTitle"><div><h2>Agent decision <code>#{selected.id}</code></h2><p>{selected.payment.customer} · {money(selected.payment.amount)} · {selected.payment.failureCode}</p></div><span className={"status "+selected.status}>{selected.status}</span></div><div className="decisionGrid"><div><small>ROOT CAUSE</small><b>{selected.rootCause}</b></div><div><small>SELECTED ACTION</small><b>{selected.recommendedAction}</b></div><div><small>RECOVERY PROBABILITY</small><b>{Math.round(selected.recoveryProbability*100)}%</b></div><div><small>EXPECTED NET RECOVERY</small><b className="accent">{money(selected.expectedNetRecovery)}</b></div><div><small>POLICY RESULT</small><b>{selected.policyReason}</b></div><div><small>STOP RULE</small><b>{selected.stoppingRule}</b></div></div><div className="reason"><h3>Why this action?</h3><p>{selected.reasoning}</p></div><div className="rank"><b>BOUNDED DECISION</b><span>Financial decisioning is deterministic; external execution is adapter-isolated.</span></div><button className="execute" disabled={busy||selected.recommendedAction==="STOP"||selected.status==="RECOVERED"||selected.status==="STOPPED"||selected.status==="BLOCKED"} onClick={execute}>{selected.recommendedAction==="STOP"||selected.status==="BLOCKED"?"BLOCKED BY POLICY":selected.status==="AWAITING_OUTCOME"?"AWAITING RECONCILIATION":selected.status==="RECOVERED"?"RECOVERY CONFIRMED":"EXECUTE RECOVERY ACTION"}</button><div className="audit"><h3>Audit timeline</h3>{audit.map(a=><div className="auditRow" key={a.id}><span>{a.eventType}</span><p>{a.details}</p></div>)}</div></>:<div className="empty"><b>Select a recovery case</b><p>Inspect diagnosis, scoring, intervention choice, policy boundary, execution state and audit trail.</p></div>}</section></div>
 :tab==="analytics"?<section className="panel analytics"><h2>Recovery intelligence</h2><div className="analyticsGrid"><div><span>Expected vs actual</span><strong>{money(dash?.expectedNetOpportunity)} → {money(dash?.recovered)}</strong></div><div><span>Confirmed recovery rate</span><strong>{dash?.recoveryRate}%</strong></div><div><span>Policy blocks / stops</span><strong>{dash?.stoppedSafely}</strong></div><div><span>Active cases</span><strong>{dash?.activeCases}</strong></div></div><p className="note">The critical metric is actual confirmed recovery. Test Mode Payment Link creation remains pending until reconciliation confirms payment.</p></section>
 :<section className="architecture panel"><h2>Bounded agent loop</h2><div className="logic">{[["01","Detect","Materialize payment, checkout, subscription, mandate or invoice event."],["02","Diagnose","Classify root cause and case context."],["03","Score","Estimate recovery probability from history, failure class, attempts, timing and risk."],["04","Optimize","Rank policy-eligible interventions by expected net recovery."],["05","Guard","Apply retry/contact budgets, high-risk blocks and merchant policy."],["06","Act","Execute exactly one bounded action through Demo or Razorpay Test adapter."],["07","Reconcile","Fetch provider state or consume signed webhook; never count link creation as recovery."],["08","Stop + Measure","Close, stop or escalate and write confirmed money to the audit ledger."]].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}</div></section>}
 </main><footer><span>REVIVEX v3.0</span><span>Synthetic by default · Test Mode when explicitly configured · No production credentials</span></footer>{toast&&<div className="toast">{toast}</div>}</div>}
createRoot(document.getElementById("root")).render(<App/>);
